"""create table chat_session

Revision ID: 12bfd26df02b
Revises: f2c9b9b2f56d
Create Date: 2026-06-15 15:33:29.173894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12bfd26df02b'
down_revision: Union[str, Sequence[str], None] = 'f2c9b9b2f56d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_chat_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_chat_message_session_id'), 'agent_chat_message', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_chat_message_user_id'), 'agent_chat_message', ['user_id'], unique=False)
    op.create_table('chat_session',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_session')
    op.drop_index(op.f('ix_agent_chat_message_user_id'), table_name='agent_chat_message')
    op.drop_index(op.f('ix_agent_chat_message_session_id'), table_name='agent_chat_message')
    op.drop_table('agent_chat_message')
    # ### end Alembic commands ###
