"""add col balance

Revision ID: 40455f33df7b
Revises: 5ca4a3f6eace
Create Date: 2026-06-16 13:44:49.309349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40455f33df7b'
down_revision: Union[str, Sequence[str], None] = '5ca4a3f6eace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('balance', sa.Integer(), nullable=True, comment='库存'))
    op.execute("UPDATE products SET balance = 0")
    # op.alter_column('products', sa.Column('balance', nullable=False))
    op.alter_column('products', 'balance', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'balance')
    # ### end Alembic commands ###
