"""add col timestamp

Revision ID: 5ca4a3f6eace
Revises: e8b09d0b1737
Create Date: 2026-06-16 13:25:24.486250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ca4a3f6eace'
down_revision: Union[str, Sequence[str], None] = 'e8b09d0b1737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_chat_message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('agent_chat_message', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('clients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('order_product', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_product', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('order_product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('products', 'deleted_at')
    op.drop_column('orders', 'deleted_at')
    op.drop_column('order_product', 'deleted_at')
    op.drop_column('order_product', 'updated_at')
    op.drop_column('order_product', 'created_at')
    op.drop_column('files', 'deleted_at')
    op.drop_column('clients', 'deleted_at')
    op.alter_column('agent_chat_message', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('agent_chat_message', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
