"""alter product add col vectorize

Revision ID: 61929252d676
Revises: 62438d5d8698
Create Date: 2026-06-16 18:22:53.238016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61929252d676'
down_revision: Union[str, Sequence[str], None] = '62438d5d8698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('vectorized', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否已向量化'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'vectorized')
    # ### end Alembic commands ###
