"""alter chatsession add col timestamp

Revision ID: 62438d5d8698
Revises: 40455f33df7b
Create Date: 2026-06-16 17:18:39.817632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62438d5d8698'
down_revision: Union[str, Sequence[str], None] = '40455f33df7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_session', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat_session', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'deleted_at')
    op.drop_column('chat_session', 'updated_at')
    op.drop_column('chat_session', 'created_at')
    # ### end Alembic commands ###
