"""add table files

Revision ID: 767cc8ff32fc
Revises: e618e0963c0b
Create Date: 2026-06-14 12:30:56.710387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767cc8ff32fc'
down_revision: Union[str, Sequence[str], None] = 'e618e0963c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件ID'),
    sa.Column('md5', sa.String(length=255), nullable=False, comment='文件MD5'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小'),
    sa.Column('file_type', sa.String(length=255), nullable=False, comment='文件类型'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
