"""rename col file_path as filepath

Revision ID: 99aac9385b2a
Revises: ace6a53518a3
Create Date: 2026-06-14 13:06:48.570875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99aac9385b2a'
down_revision: Union[str, Sequence[str], None] = 'ace6a53518a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('original_filename', sa.String(length=255), nullable=False, comment='文件名'))
    op.add_column('files', sa.Column('filepath', sa.String(length=255), nullable=False, comment='文件路径'))
    op.add_column('files', sa.Column('filesize', sa.Integer(), nullable=False, comment='文件大小'))
    op.add_column('files', sa.Column('filetype', sa.String(length=255), nullable=False, comment='文件类型'))
    op.drop_column('files', 'filename')
    op.drop_column('files', 'file_type')
    op.drop_column('files', 'file_path')
    op.drop_column('files', 'file_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False, comment='文件大小'))
    op.add_column('files', sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件路径'))
    op.add_column('files', sa.Column('file_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件类型'))
    op.add_column('files', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件名'))
    op.drop_column('files', 'filetype')
    op.drop_column('files', 'filesize')
    op.drop_column('files', 'filepath')
    op.drop_column('files', 'original_filename')
    # ### end Alembic commands ###
