"""create table products

Revision ID: a64f28aa4486
Revises: 12bfd26df02b
Create Date: 2026-06-16 09:01:30.763844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a64f28aa4486'
down_revision: Union[str, Sequence[str], None] = '12bfd26df02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False, comment='产品ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='产品名称'),
    sa.Column('description', sa.String(length=255), nullable=False, comment='产品描述'),
    sa.Column('price', sa.Float(), nullable=False, comment='产品价格'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
