"""rename table files as file

Revision ID: cbbfbcc8f511
Revises: c345f4ea1804
Create Date: 2026-06-14 12:52:04.497375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbbfbcc8f511'
down_revision: Union[str, Sequence[str], None] = 'c345f4ea1804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件ID'),
    sa.Column('md5', sa.String(length=255), nullable=False, comment='文件MD5'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='文件路径'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小'),
    sa.Column('file_type', sa.String(length=255), nullable=False, comment='文件类型'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('file_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='文件ID'),
    sa.Column('md5', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件MD5'),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件名'),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件路径'),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False, comment='文件大小'),
    sa.Column('file_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='文件类型'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('file_info_pkey'))
    )
    op.drop_table('file')
    # ### end Alembic commands ###
