"""alter add col remark

Revision ID: e8b09d0b1737
Revises: ed17481df6dd
Create Date: 2026-06-16 10:05:57.655341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b09d0b1737'
down_revision: Union[str, Sequence[str], None] = 'ed17481df6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'remark')
    # ### end Alembic commands ###
