"""create table client

Revision ID: eb06fc2a6a06
Revises: f2b649d4afae
Create Date: 2026-06-15 12:31:06.471353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb06fc2a6a06'
down_revision: Union[str, Sequence[str], None] = 'f2b649d4afae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False, comment='客户ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('mobile', sa.String(length=255), nullable=False, comment='电话'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
