"""add col vectorize

Revision ID: f2b649d4afae
Revises: 99aac9385b2a
Create Date: 2026-06-15 11:19:17.795089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2b649d4afae'
down_revision: Union[str, Sequence[str], None] = '99aac9385b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('vectorized', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否已向量化'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'vectorized')
    # ### end Alembic commands ###
